### ISSUE TITLE
Facilidades para la importación y exportación masiva de datos

### ISSUE THREAD

**Issue by marian-vignau** [PyAr/OpenLex#10]
Particularmente de los escritos realizados.
ckEditor almacena los escritos en formato HTML. 
Con lexdoctor se puede usar https://github.com/marian-vignau/pylexcom (funcionaba en versiones algo viejitas)

**Comment by chazuttu** [comment]
Entonces, ¿qué se tiene que hacer básicamente en él?

**Comment by elvisdiazsoftfolio** [comment]
Hola, como se podría realizar lo siguiente a esta tarea?

**Comment by Juerodriguez** [comment]
> Hola, como se podría realizar lo siguiente a esta tarea?

Buenas @elvisdiazsoftfolio estas trabajando en algo? Me interesaria desarrollar esta issue.

**Comment by Juerodriguez** [comment]
Problema en la importacion de csv [https://github.com/PyAr/OpenLex/pull/26#issuecomment-825316199](url)

**Comment by eamanu** [comment]
Hola @Juerodriguez Me parece que según lo que menciones en el último comentario, tienes una propuesta
 que funciona. Querés hacer el PR? y de último lo discutimos allí

**Comment by Juerodriguez** [comment]
He estado buscando la solución y encontre que ya esta aplicada en el módulo pydal , el asunto que ese ultimo PR aún no esta en la versión estable de web2py la solución que le dí fue:

1. Quitar la carpeta dal de web2py/gloun/packages.
2. Clonar pydal de su repositorio (https://github.com/web2py/pydal.git)
3. Renombrar web2py/gloun/packages/pydal por web2py/gloun/packages/dal

https://github.com/web2py/web2py/issues/1609#issuecomment-846044105

**Comment by eamanu** [comment]
@Juerodriguez #36  was merged, this ticket can be close?

cc: @marian-vignau

**Comment by Juerodriguez** [comment]
> @Juerodriguez #36 was merged, this ticket can be close?
> 
> cc: @marian-vignau

I think we can close when PR https://github.com/PyAr/OpenLex/pull/41 will be merge, because in that PR is the feature  that download the writings, I only have to create the pdf as temporary files, today I will be solving that
