### ISSUE TITLE
2 repositorios de OpenLex

### ISSUE THREAD

**Issue by R0shyx** [PyAr/OpenLex#19]
Por curiosidad: ¿a qué se debe que haya 2 repositorios de OpenLex en Github?
El otro es https://github.com/marian-vignau/openlex

**Comment by R0shyx** [comment]
Se supondría que el de https://github.com/marian-vignau/openlex debería ser el oficial...

**Comment by eamanu** [comment]
@R0shyx, un poco tarde la respuesta, pero según Github, este repositorio, el de PyAr es el oficila y 
el de marian sería un "fork". 

No sé como habrá sido en el 2019 pero (por ahora)  esté sería el  oficial 

cc: @marian-vignau
